### ISSUE TITLE
Initialization of Intrinsics fails: Need min. one observation

### ISSUE THREAD

**Issue by zimmerm** [ethz-asl/kalibr#104]
Hi!

I'm running Kalibr in its offline CDE version and I'm trying to calibrate a multi camera setup with it.
Because my cameras are rather low res, noisy and far appart I decided to create a 3x3 Apriltag board with large markers on it (15cm tagsize with 3cm spacing; using the provided tool).
I managed to get the 'Multiple camera calibration' example working and to write my own images to a bag file. When running the calibration with 
`kalibr_calibrate_cameras --bag ./calib_eq/calib_data.bag --topics /cam0/image_raw/ /cam1/image_raw/ --models pinhole-radtan pinhole-radtan --target ./tags/my_april.yaml --show_extraction`
I can see the images running by, but without any detections in it and the 'Corner reprojection' window remains empty too. Therefore the calibration process fails with:

> Traceback (most recent call last):
  File "/var/kalibr-build/devel/bin/kalibr_calibrate_cameras", line 5, in <module>
    exec(fh.read())
  File "<string>", line 444, in <module>
  File "<string>", line 182, in main
  File "/var/kalibr-build/src/kalibr/aslam_offline_calibration/kalibr/python/kalibr_camera_calibration/CameraCalibrator.py", line 55, in initGeometryFromObservations
    success = self.geometry.initializeIntrinsics(observations)
RuntimeError: [Exception] /var/kalibr-build/src/kalibr/aslam_cv/aslam_cameras/include/aslam/cameras/implementation/PinholeProjection.hpp:713: initializeIntrinsics() assert(observations.size() != 0) failed: Need min. one observation
 
For visualization I added one of the images, Im using for calibration. I think the quality is fairly good and that marker extraction should be able to find markers in it.
![1000000002000000000](https://cloud.githubusercontent.com/assets/19664895/26620132/cac36614-45e1-11e7-89e3-dbd76f29ca8a.png)

My tag configuration file reads as:

> target_type: 'aprilgrid' #gridtype
tagCols: 3               #number of apriltags
tagRows: 3               #number of apriltags
tagSize: 0.15           #size of apriltag, edge to edge [m]
tagSpacing: 0.20          #ratio of space between tags to tagSize

Any ideas on what is going wrong here and what I can try?

**Comment by zimmerm** [comment]
The reason was that the images got mirrored at some point, which turned each tag into an invalid one.
