### ISSUE TITLE
RuntimeError: Optimization failed!

### ISSUE THREAD

**Issue by derekhe89** [ethz-asl/kalibr#116]
when I used kalibr calibrate imu and camera  ,it appeared " RuntimeError: Optimization failed!",my imu frequency is 60hz and camera requency is 20hz.
       The message printed by the terminal is as follows：
importing libraries
Initializing IMUs:
  Update rate: 60.0
  Accelerometer:
    Noise density: 0.08 
    Noise density (discrete): 0.619677335393 
    Random walk: 0.1
  Gyroscope:
    Noise density: 0.012
    Noise density (discrete): 0.092951600309 
    Random walk: 0.03
Initializing imu rosbag dataset reader:
	Dataset:          /home/hl/kalibr_workspace/mynteye_cameraimu_calib_711_2.bag
	Topic:            /imu0
bagstart 38726.1760527
baglength 69.95136093
[ WARN] [1499821758.521938]: BagImuDatasetReader: truncated 1801 / 4168 messages.
	Number of messages: 4168
Reading IMU data (/imu0)
  Read 2367 imu readings over 40.0 seconds                       
Initializing calibration target:
  Type: aprilgrid
  Tags: 
    Rows: 6
    Cols: 6
    Size: 0.024 [m]
    Spacing 0.0072 [m]
Initializing camera chain:
Camera chain - cam0:
  Camera model: pinhole
  Focal length: [365.9021105354135, 371.1036033722559]
  Principal point: [385.6213176029975, 231.80948369303306]
  Distortion model: radtan
  Distortion coefficients: [-0.20973302237135366, 0.050948220015473986, 0, 0]
  baseline: no data available
Camera chain - cam1:
  Camera model: pinhole
  Focal length: [365.9021105354135, 371.1036033722559]
  Principal point: [359.5612415709596, 245.46363443410945]
  Distortion model: radtan
  Distortion coefficients: [-0.20607131885372323, 0.028903158396448237, 0.00180571880675569, -0.00553860461961384]
  baseline: [[   0.99981575   -0.00194901    0.01909619 -118.64005405]
 [   0.00190259    0.99999519    0.00244903   -0.38026237]
 [  -0.01910087   -0.00241225    0.99981465    0.76019651]
 [   0.            0.            0.            1.        ]]
Initializing camera rosbag dataset reader:
	Dataset:          /home/hl/kalibr_workspace/mynteye_cameraimu_calib_711_2.bag
	Topic:            /cam0/image_raw
[ WARN] [1499821765.038307]: BagImageDatasetReader: truncated 597 / 1387 images.
	Number of images: 1387
Extracting calibration target corners
  Extracted corners for 790 images (of 790 images)                              
Initializing camera rosbag dataset reader:
	Dataset:          /home/hl/kalibr_workspace/mynteye_cameraimu_calib_711_2.bag
	Topic:            /cam1/image_raw
[ WARN] [1499821792.498072]: BagImageDatasetReader: truncated 597 / 1387 images.
	Number of images: 1387
Extracting calibration target corners
  Extracted corners for 790 images (of 790 images)                              
Baseline between cam0 and cam1 set to:
T=  [[   0.99981575   -0.00194901    0.01909619 -118.64005405]
 [   0.00190259    0.99999519    0.00244903   -0.38026237]
 [  -0.01910087   -0.00241225    0.99981465    0.76019651]
 [   0.            0.            0.            1.        ]]
Baseline:  118.64309893  [m]

Building the problem
	Spline order: 6
	Pose knots per second: 70
	Do pose motion regularization: False
		xddot translation variance: 1000000.000000
		xddot rotation variance: 100000.000000
	Bias knots per second: 50
	Do bias motion regularization: True
	Blake-Zisserman on reprojection errors -1
	Acceleration Huber width (m/s^2): -1.000000
	Gyroscope Huber width (rad/s): -1.000000
	Do time calibration: False
	Max iterations: 30
	Time offset padding: 0.020000

Estimating imu-camera rotation prior

Initializing a pose spline with 3999 knots (100.000000 knots per second over 39.987373 seconds)
  Orientation prior camera-imu found as: (T_i_c)
[[ 0.22926164 -0.97336483 -0.00012715]
 [-0.86929292 -0.20469027 -0.44992413]
 [ 0.43791429  0.10326088 -0.89306677]]
  Gyro bias prior found as: (b_gyro)
[ 0.00338471  0.00749472 -0.00233749]

Initializing a pose spline with 4007 knots (100.000000 knots per second over 40.067373 seconds)

Initializing the bias splines with 2003 knots

Adding camera error terms (/cam0/image_raw)
  Added 790 camera error terms                                    

Adding camera error terms (/cam1/image_raw)
  Added 790 camera error terms                               

Adding accelerometer error terms (/imu0)
  Added 2361 of 2367 accelerometer error terms (skipped 6 out-of-bounds measurements)

Adding gyroscope error terms (/imu0)
  Added 2361 of 2367 gyroscope error terms (skipped 6 out-of-bounds measurements)

Before Optimization
===================
Reprojection error squarred (cam0):  mean 12.8028091742, median 9.75447600516, std: 11.5605080536
Reprojection error squarred (cam1):  mean 8.6651943264e+22, median 8.49084016378e+22, std: 1.17782393194e+22
Gyro error squarred (imu0):          mean 0.791447975186, median 0.462366599838, std: 1.03892846984
Accelerometer error squarred (imu0): mean 408.244322382, median 408.493369611, std: 19.9155802126

Transformation T_cam0_imu0 (imu0 to cam0, T_ci): [m]
[[ 0.22926164 -0.97336483 -0.00012715  0.        ]
 [-0.86929292 -0.20469027 -0.44992413  0.        ]
 [ 0.43791429  0.10326088 -0.89306677  0.        ]
 [ 0.          0.          0.          1.        ]]

Transformation T_cam1_imu0 (imu0 to cam1, T_ci): [m]
[[   0.23927616   -0.97081465   -0.01630439 -118.64005405]
 [  -0.86778008   -0.20628831   -0.45210936   -0.38026237]
 [   0.43555098    0.12232762   -0.89181349    0.76019651]
 [   0.            0.            0.            1.        ]]

Optimizing...
No linear system solver set in the options. Defaulting to the sparse_cholesky solver
Using the sparse_cholesky linear system solver
Using the levenberg_marquardt trust region policy
No linear system solver set in the options. Defaulting to the sparse_cholesky solver
Using the sparse_cholesky linear system solver
Using the levenberg_marquardt trust region policy
Initializing
Optimization problem initialized with 8031 design variables and 216340 error terms
The Jacobian matrix is 501498 x 36128
[0.0]: J: 9.26474e+27
CHOLMOD warning: matrix not positive definite
Cholmod warning: matrix not positive definite.Solution failed
[WARNING] System solution failed
CHOLMOD warning: matrix not positive definite
Cholmod warning: matrix not positive definite.Solution failed
[WARNING] System solution failed
CHOLMOD warning: matrix not positive definite
Cholmod warning: matrix not positive definite.Solution failed
[WARNING] System solution failed
CHOLMOD warning: matrix not positive definite
Cholmod warning: matrix not positive definite.Solution failed
[WARNING] System solution failed
[1]: J: 1.48293e+27, dJ: 7.78181e+27, deltaX: 1.21073, LM - lambda:1.6384e+06 mu:32
[2]: J: 2.37395e+26, dJ: 1.24553e+27, deltaX: 1.54686, LM - lambda:1.12351e+06 mu:2
[3]: J: 3.80677e+25, dJ: 1.99327e+26, deltaX: 1.75055, LM - lambda:770510 mu:2
[4]: J: 6.12147e+24, dJ: 3.19462e+25, deltaX: 1.44042, LM - lambda:528998 mu:2
[5]: J: 9.83745e+23, dJ: 5.13773e+24, deltaX: 1.04445, LM - lambda:363843 mu:2
[6]: J: 1.57085e+23, dJ: 8.2666e+23, deltaX: 1.61585, LM - lambda:250148 mu:2
[7]: J: 2.48698e+22, dJ: 1.32215e+23, deltaX: 2.32317, LM - lambda:171271 mu:2
[8]: J: 3.98267e+21, dJ: 2.08871e+22, deltaX: 2.63623, LM - lambda:116616 mu:2
Last step was a regression. Reverting
[9]: J: 5.73604e+52, dJ: -5.73604e+52, deltaX: 7.30801, LM - lambda:79994 mu:2
Last step was a regression. Reverting
[10]: J: 1.26861e+43, dJ: -1.26861e+43, deltaX: 6.53475, LM - lambda:319976 mu:4
[11]: J: 8.03123e+20, dJ: 3.17954e+21, deltaX: 11.9327, LM - lambda:2.55981e+06 mu:8
Last step was a regression. Reverting
[12]: J: 4.16735e+37, dJ: -4.16735e+37, deltaX: 4.86485, LM - lambda:853269 mu:2
[13]: J: 1.74788e+20, dJ: 6.28335e+20, deltaX: 2.83686, LM - lambda:3.41308e+06 mu:4
[14]: J: 3.97087e+19, dJ: 1.35079e+20, deltaX: 2.0593, LM - lambda:1.13769e+06 mu:2
[15]: J: 3.07972e+18, dJ: 3.6629e+19, deltaX: 3.77783, LM - lambda:952864 mu:2
[16]: J: 4.26696e+17, dJ: 2.65302e+18, deltaX: 1.40632, LM - lambda:378088 mu:2
[17]: J: 6.40135e+16, dJ: 3.62683e+17, deltaX: 1.49582, LM - lambda:235224 mu:2
[18]: J: 9.91776e+15, dJ: 5.40957e+16, deltaX: 1.78318, LM - lambda:154530 mu:2
[19]: J: 1.55815e+15, dJ: 8.35961e+15, deltaX: 2.11962, LM - lambda:103721 mu:2
[20]: J: 2.43307e+14, dJ: 1.31484e+15, deltaX: 2.50866, LM - lambda:70249.5 mu:2
[21]: J: 3.74487e+13, dJ: 2.05858e+14, deltaX: 2.93169, LM - lambda:47348.7 mu:2
[22]: J: 5.85721e+12, dJ: 3.15915e+13, deltaX: 3.21896, LM - lambda:31459.8 mu:2
[23]: J: 9.46618e+11, dJ: 4.91059e+12, deltaX: 3.4556, LM - lambda:20669.4 mu:2
[24]: J: 1.57898e+11, dJ: 7.8872e+11, deltaX: 4.86574, LM - lambda:12927.6 mu:2
[25]: J: 3.71957e+10, dJ: 1.20702e+11, deltaX: 6.45896, LM - lambda:7551.89 mu:2
[26]: J: 1.57554e+10, dJ: 2.14404e+10, deltaX: 9.99821, LM - lambda:5408.06 mu:2
[27]: J: 1.13311e+10, dJ: 4.42425e+09, deltaX: 10.4157, LM - lambda:4652.96 mu:2
[28]: J: 6.52273e+09, dJ: 4.8084e+09, deltaX: 27.2034, LM - lambda:1550.99 mu:2
[29]: J: 3.91925e+09, dJ: 2.60348e+09, deltaX: 41.6308, LM - lambda:516.996 mu:2
[30]: J: 3.4804e+09, dJ: 4.38844e+08, deltaX: 35.1416, LM - lambda:172.332 mu:2
[ERROR] [1499821955.400941]: Optimization failed!
Traceback (most recent call last):
  File "/var/kalibr-build/devel/bin/kalibr_calibrate_imu_camera", line 5, in <module>
    exec(fh.read())
  File "<string>", line 206, in <module>
  File "<string>", line 182, in main
  File "/var/kalibr-build/src/kalibr/aslam_offline_calibration/kalibr/python/kalibr_imu_camera_calibration/IccCalibrator.py", line 181, in optimize
    raise RuntimeError("Optimization failed!")
RuntimeError: Optimization failed!
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/apport_python_hook.py", line 64, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
ImportError: No module named apport.fileutils

Original exception was:
Traceback (most recent call last):
  File "/var/kalibr-build/devel/bin/kalibr_calibrate_imu_camera", line 5, in <module>
    exec(fh.read())
  File "<string>", line 206, in <module>
  File "<string>", line 182, in main
  File "/var/kalibr-build/src/kalibr/aslam_offline_calibration/kalibr/python/kalibr_imu_camera_calibration/IccCalibrator.py", line 181, in optimize
    raise RuntimeError("Optimization failed!")
RuntimeError: Optimization failed!

**Comment by yangtzey** [comment]
I have the same problem with you. Have you solved this problem?

**Comment by vishals1010** [comment]
hi, have you solved this issue ....?

**Comment by lapchun** [comment]
It's mainly because you don't record the .bag file in a right way.
Maybe this will help:
https://github.com/ethz-asl/kalibr/wiki/camera-imu-calibration

**Comment by yangtzey** [comment]
这是来自QQ邮箱的假期自动回复邮件。
自动回复

**Comment by yangtzey** [comment]
这是来自QQ邮箱的假期自动回复邮件。
自动回复
