### ISSUE TITLE
RuntimeError: TimeWentBackwardsException

### ISSUE THREAD

**Issue by voyageanp** [ethz-asl/kalibr#127]
I have got this runtimeerror, and could you kindly teach me how to remove this error 
Best
```
kalibr_calibrate_imu_camera --target april_6x6.yaml --cam cam.yaml --imu imu.yaml --bag 2017-08-08-16-24-37.bag --perform-synchronization
importing libraries
Initializing IMUs:
  Update rate: 200
  Accelerometer:
    Noise density: 0.1 
    Noise density (discrete): 1.41421356237 
    Random walk: 0.005
  Gyroscope:
    Noise density: 0.005
    Noise density (discrete): 0.0707106781187 
    Random walk: 4e-06
Initializing imu rosbag dataset reader:
	Dataset:          2017-08-08-16-24-37.bag
	Topic:            /r430_tm1/imu_raw
Traceback (most recent call last):
  File "/home/user/catkin_ws/devel/bin/kalibr_calibrate_imu_camera", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/user/catkin_ws/src/kalibr_workspace/src/Kalibr/aslam_offline_calibration/kalibr/python/kalibr_calibrate_imu_camera", line 236, in <module>
    main()
  File "/home/user/catkin_ws/src/kalibr_workspace/src/Kalibr/aslam_offline_calibration/kalibr/python/kalibr_calibrate_imu_camera", line 151, in main
    estimateTimedelay=parsed.estimate_imu_delay) )
  File "/home/user/catkin_ws/src/kalibr_workspace/src/Kalibr/aslam_offline_calibration/kalibr/python/kalibr_imu_camera_calibration/IccSensors.py", line 592, in __init__
    parsed.bag_from_to, parsed.perform_synchronization)
  File "/home/user/catkin_ws/src/kalibr_workspace/src/Kalibr/aslam_offline_calibration/kalibr/python/kalibr_imu_camera_calibration/IccSensors.py", line 33, in initImuBagDataset
    perform_synchronization=perform_synchronization)
  File "/home/user/catkin_ws/src/kalibr_workspace/src/Kalibr/aslam_offline_calibration/kalibr/python/kalibr_common/ImuDatasetReader.py", line 44, in __init__
    self.indices = self. sortByTime(self.indices)
  File "/home/user/catkin_ws/src/kalibr_workspace/src/Kalibr/aslam_offline_calibration/kalibr/python/kalibr_common/ImuDatasetReader.py", line 60, in sortByTime
    stamp.to_sec())
RuntimeError: [TimeWentBackwardsException] /home/user/catkin_ws/src/kalibr_workspace/src/Kalibr/Schweizer-Messer/sm_timing/include/sm/timing/implementation/TimestampCorrector.hpp:26: correctTimestamp() assert(remoteTime > _convexHull[_convexHull.size() - 1].x) failed [1.50218e+09 > 1.50218e+09]: The correction algorithm requires that times are passed in with monotonically increasing remote timestamps
```

**Comment by vishals1010** [comment]
is this issue solved, i get the same issue

**Comment by goldbattle** [comment]
Correct your driver as it is publishing timestamps in a non-monotonically fashion.
