### ISSUE TITLE
Wiki page "Yaml formats" does not mention rostopic field for IMU config

### ISSUE THREAD

**Issue by pkok** [ethz-asl/kalibr#14]
The [wiki page describing the YAML formats](https://github.com/ethz-asl/kalibr/wiki/yaml-formats) describes all required fields for the YAML files except for `rostopic` for the IMU configuration. 

During a run of `rosrun kalibr kalibr_calibrate_imu_camera --time-calibration --bag some.bag --cam cam_config.yaml --imu imu_config.yaml --target target_config.yaml` I get the output:

```
importing libraries
Initializing IMUs:
  Update rate: 100
  Accelerometer:
    Noise density: 0.004 
    Noise density (discrete): 0.04 
    Random walk: 0.02
  Gyroscope:
    Noise density: 0.1
    Noise density (discrete): 1.0 
    Random walk: 1.0
Traceback (most recent call last):
  File "/home/pkok/ros/repos/kalibr/src/aslam_offline_calibration/kalibr/python/kalibr_calibrate_imu_camera", line 206, in <module>
    main()
  File "/home/pkok/ros/repos/kalibr/src/aslam_offline_calibration/kalibr/python/kalibr_calibrate_imu_camera", line 138, in main
    imus.append( sens.IccImu(imuConfig, parsed) )
  File "/home/pkok/ros/repos/kalibr/src/aslam_offline_calibration/kalibr/python/kalibr_imu_camera_calibration/IccSensors.py", line 511, in __init__
    self.dataset = initImuBagDataset(parsed.bagfile[0], imuConfig.getRosTopic(), parsed.bag_from_to)
  File "/home/pkok/ros/repos/kalibr/src/aslam_offline_calibration/kalibr/python/kalibr_common/ConfigReader.py", line 123, in func
    args[0].raiseError("Field {0} missing in file: {1}".format(e, args[0].yamlFile))
  File "/home/pkok/ros/repos/kalibr/src/aslam_offline_calibration/kalibr/python/kalibr_common/ConfigReader.py", line 169, in raiseError
    raise RuntimeError( "{0}{1}".format(header, message) )
RuntimeError: [ImuConfig Reader]: Field 'rostopic' missing in file: repos/kalibr/config/imu/MTx.yaml
```

Adding a field `rostopic` in `imu_config.yaml` which refers to a topic with message type `sensor_msgs/Imu` resolves this error.

_Suggested solution:_ Add some documentation about this field in [Yaml formats](https://github.com/ethz-asl/kalibr/wiki/yaml-formats).

**Comment by v0n0** [comment]
+1 this fixed the error for me

**Comment by sunbinbin1991** [comment]
I have same problem,then add"rostopic: /imu0" in imu.yaml ,it's ok.

**Comment by rehderj** [comment]
Thanks for raising this issue. I just fixed it.
