### ISSUE TITLE
timeshift_cam_imu failed

### ISSUE THREAD

**Issue by caoxudong0513** [ethz-asl/kalibr#148]
hello,Can anyone tell me how to solve this problem?
thanks

Optimizing...
Using the block_cholesky linear system solver
Using the levenberg_marquardt trust region policy
Using the block_cholesky linear system solver
Using the levenberg_marquardt trust region policy
Initializing
Optimization problem initialized with 9028 design variables and 15074 error terms
The Jacobian matrix is 41444 x 40611
[0.0]: J: 1.49576e+09
Exception in thread block: [aslam::Exception] /home/caoxudong/kalibr/src/kalibr-master/aslam_nonparametric_estimation/aslam_splines/src/BSplineExpressions.cpp:447: toTransformationMatrixImplementation() assert(_bufferTmin <= _time.toScalar() < _bufferTmax) failed [1.5142e+09 <= 1.5142e+09 < 1.5142e+09]: Spline Coefficient Buffer Exceeded. Set larger buffer margins!
Exception in thread block: [aslam::Exception] /home/caoxudong/kalibr/src/kalibr-master/aslam_nonparametric_estimation/aslam_splines/src/BSplineExpressions.cpp:447: toTransformationMatrixImplementation() assert(_bufferTmin <= _time.toScalar() < _bufferTmax) failed [1.5142e+09 <= 1.5142e+09 < 1.5142e+09]: Spline Coefficient Buffer Exceeded. Set larger buffer margins!
[ERROR] [1514211072.850258]: Optimization failed!
Traceback (most recent call last):
  File "/home/caoxudong/kalibr/devel/bin/kalibr_calibrate_imu_camera", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/caoxudong/kalibr/src/kalibr-master/aslam_offline_calibration/kalibr/python/kalibr_calibrate_imu_camera", line 236, in <module>
    main()
  File "/home/caoxudong/kalibr/src/kalibr-master/aslam_offline_calibration/kalibr/python/kalibr_calibrate_imu_camera", line 206, in main
    iCal.optimize(maxIterations=parsed.max_iter, recoverCov=parsed.recover_cov)
  File "/home/caoxudong/kalibr/src/kalibr-master/aslam_offline_calibration/kalibr/python/kalibr_imu_camera_calibration/IccCalibrator.py", line 180, in optimize
    raise RuntimeError("Optimization failed!")
RuntimeError: Optimization failed!

**Comment by JohnnyYeh** [comment]
you can use some optional arguments,such as  --timeoffset-padding TIMEOFFSET_PADDING
