### ISSUE TITLE
Optimization failed in kalibr_calibration_imu_camera ( single imu and single camera)

### ISSUE THREAD

**Issue by Apathy1234** [ethz-asl/kalibr#239]
Hi ! I have tested my dataset acquired today( about 1min35sec). The frequency of imu is 350Hz( camera is 20Hz). I want to know how to solve the following problem( I have tried set the --timeoffset-Padding). Thanks!

The Jacobian matrix is 611724 x 68068
[0.0]: J: 1.13475e+08
[1]: J: 6.35456e+07, dJ: 4.99297e+07, deltaX: 0.423639, LM - lambda:10 mu:2
Exception in thread block: [aslam::Exception] /home/dxy/kalibr_workspace/src/Kalibr/aslam_nonparametric_estimation/aslam_splines/src/BSplineExpressions.cpp:447: toTransformationMatrixImplementation() assert(_bufferTmin <= _time.toScalar() < _bufferTmax) failed [1.54193e+09 <= 1.54193e+09 < 1.54193e+09]: Spline Coefficient Buffer Exceeded. Set larger buffer margins!
Exception in thread block: [aslam::Exception] /home/dxy/kalibr_workspace/src/Kalibr/aslam_nonparametric_estimation/aslam_splines/src/BSplineExpressions.cpp:447: toTransformationMatrixImplementation() assert(_bufferTmin <= _time.toScalar() < _bufferTmax) failed [1.54193e+09 <= 1.54193e+09 < 1.54193e+09]: Spline Coefficient Buffer Exceeded. Set larger buffer margins!
Exception in thread block: [aslam::Exception] /home/dxy/kalibr_workspace/src/Kalibr/aslam_nonparametric_estimation/aslam_splines/src/BSplineExpressions.cpp:447: toTransformationMatrixImplementation() assert(_bufferTmin <= _time.toScalar() < _bufferTmax) failed [1.54193e+09 <= 1.54193e+09 < 1.54193e+09]: Spline Coefficient Buffer Exceeded. Set larger buffer margins!
[ERROR] [1541988992.745338]: Optimization failed!
Traceback (most recent call last):
  File "/home/dxy/kalibr_workspace/devel/bin/kalibr_calibrate_imu_camera", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/dxy/kalibr_workspace/src/Kalibr/aslam_offline_calibration/kalibr/python/kalibr_calibrate_imu_camera", line 236, in <module>
    main()
  File "/home/dxy/kalibr_workspace/src/Kalibr/aslam_offline_calibration/kalibr/python/kalibr_calibrate_imu_camera", line 206, in main
    iCal.optimize(maxIterations=parsed.max_iter, recoverCov=parsed.recover_cov)
  File "/home/dxy/kalibr_workspace/src/Kalibr/aslam_offline_calibration/kalibr/python/kalibr_imu_camera_calibration/IccCalibrator.py", line 179, in optimize
    raise RuntimeError("Optimization failed!")
RuntimeError: Optimization failed!

**Comment by gethubwy** [comment]
Hello Apathy1234 , I have also met this problem, do you solved it?
  I have tested my dataset acquired yesterday, But after a long time wait, it shows that is Optimization failed! I want to know how do you deal with it, Thank you in advance.
"assert(_bufferTmin <= _time.toScalar() < _bufferTmax) failed [1.56264e+09 <= 1.56264e+09 < 1.56264e+09]: Spline Coefficient Buffer Exceeded. Set larger buffer margins!"
![image](https://user-images.githubusercontent.com/26212984/60933637-b4789780-a2f5-11e9-9ea9-b1500a23654a.png)

**Comment by Nowornever666** [comment]
Hello, I also met this problem, do you solve it? @gethubwy

**Comment by JiangXiuXiang** [comment]
hi,I have not read the code ,and don't know why.But this problem can be solved by adding "--timeoffset-padding 0.1" at the end of the command. If the problem is still exists, you can increase the number , such as "--timeoffset-padding 0.5", and try again.

example usage:
`kalibr_calibrate_imu_camera --target april_50x50.yaml --cam camchain-.data.yaml --imu imu.yaml --bag data.bag --timeoffset-padding 0.1`

**Comment by chongjeelee** [comment]
i have the same problem!
i try to reduce the imu_cam data ,and also increase the timeoffset-padding,the  problem solved!but i found the LM optimize is very very slow...maybe take hours!

**Comment by JiangXiuXiang** [comment]
您好，您的邮件已经收到。我将在近期拜读，尽快给您回复。

**Comment by leoheung** [comment]
> hi,I have not read the code ,and don't know why.But this problem can be solved by adding "--timeoffset-padding 0.1" at the end of the command. If the problem still exists, you can increase the number , such as "--timeoffset-padding 0.5", and try again.
> 
> example usage: `kalibr_calibrate_imu_camera --target april_50x50.yaml --cam camchain-.data.yaml --imu imu.yaml --bag data.bag --timeoffset-padding 0.2`

Thanks. This solved my problem.
