### ISSUE TITLE
CDE package ｄｏｎ＇ｔ support FOV model?

### ISSUE THREAD

**Issue by LittleMing233** [ethz-asl/kalibr#248]
Ｈｅｌｌｏ， I use CDE package to calibrate my camera, i found that the Kalibr support the fov distortion model in
[Supported model](https://github.com/ethz-asl/kalibr/wiki/supported-models).
it has a mistake as below:
```
kalibr-cde ./kalibr_calibrate_cameras --bag /home/littleming/Desktop/ueyecam.bag --topics /cam0/image_raw --models pinhole-fov --target /home/littleming/Desktop/hahaha.yaml
importing libraries
Initializing cam0:
	Camera model:	  pinhole-fov
Traceback (most recent call last):
  File "/var/kalibr-build/devel/bin/kalibr_calibrate_cameras", line 5, in <module>
    exec(fh.read())
  File "<string>", line 444, in <module>
  File "<string>", line 190, in main
RuntimeError: Unknown camera model: pinhole-fov. Try ['pinhole-radtan', 'pinhole-equi', 'omni-radtan'].
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/apport_python_hook.py", line 64, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
ImportError: No module named apport.fileutils

Original exception was:
Traceback (most recent call last):
  File "/var/kalibr-build/devel/bin/kalibr_calibrate_cameras", line 5, in <module>
    exec(fh.read())
  File "<string>", line 444, in <module>
  File "<string>", line 190, in main
RuntimeError: Unknown camera model: pinhole-fov. Try ['pinhole-radtan', 'pinhole-equi', 'omni-radtan'].

```
Does the CDE version not support fov model?

Thanks!

**Comment by schneith** [comment]
The FOV model was later added to kalibr is not supported by the CDE version.
