### ISSUE TITLE
validator crashes due to C++ signature

### ISSUE THREAD

**Issue by ibaranov-cp** [ethz-asl/kalibr#263]
I'm getting the following error, running in VMWare Player, after running kalibr to get calibration.

```
[ERROR] [1550093626.097650]: bad callback: <bound method Subscriber.callback of <message_filters.Subscriber object at 0x7f041f06fe10>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/message_filters/__init__.py", line 75, in callback
    self.signalMessage(msg)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/message_filters/__init__.py", line 57, in signalMessage
    cb(*(msg + args))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/message_filters/__init__.py", line 224, in add
    self.signalMessage(*msgs)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/message_filters/__init__.py", line 57, in signalMessage
    cb(*(msg + args))
  File "/home/ubuntu/catkin_ws/src/Kalibr/aslam_offline_calibration/kalibr/python/kalibr_camera_validator", line 136, in synchronizedCallback
    success, observation = validator.target.detector.findTarget( np_image)
ArgumentError: Python argument types in
    GridDetector.findTarget(GridDetector, numpy.ndarray)
did not match C++ signature:
    findTarget(aslam::cameras::GridDetector*, Eigen::Matrix<unsigned char, -1, -1, 0, -1, -1>)
    findTarget(aslam::cameras::GridDetector*, aslam::Time, Eigen::Matrix<unsigned char, -1, -1, 0, -1, -1>)
```

Any ideas on next steps?

**Comment by goldbattle** [comment]
Can you please try PR https://github.com/ethz-asl/kalibr/pull/515 to see if this fixes the issue for you. From the looks it didn't compile the code successfully. What exact script are you running to get this error?
