### ISSUE TITLE
Undefined Symbol in libsm_logging

### ISSUE THREAD

**Issue by GerdHel** [ethz-asl/kalibr#264]
When calling 

> kalibr_calibrate_imu_camera --target april_6x6.yaml --cam camchain.yaml --imu imu_adis16448.yaml --bag dynamic.bag --bag-from-to 5 45 

which has build from source I get the following error: 

`importing libraries
Traceback (most recent call last):
  File ".../kalibr_workspace/devel/bin/kalibr_calibrate_imu_camera", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File ".../kalibr_workspace/src/Kalibr/aslam_offline_calibration/kalibr/python/kalibr_calibrate_imu_camera", line 3, in <module>
    import sm
  File ".../kalibr_workspace/devel/lib/python2.7/dist-packages/sm/__init__.py", line 35, in <module>
    exec(__fh.read())
  File "<string>", line 4, in <module>
ImportError: /.../kalibr_workspace/devel/lib/libsm_logging.so: undefined symbol: _ZN5boost16re_detail_10690013put_mem_blockEPv
`

All other kalibr executables yield the same error when they depend on the libsm_logging.so.

My system setup is the following:

- Ubuntu 18.04 (bionic)
- ros-melodic
- boost 1.69.0
- gcc/g++ 7.3.0

**Comment by GerdHel** [comment]
Calling l_dd libsm_logging.so_ outputs the following:

`	linux-vdso.so.1 (0x00007ffc300a4000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6dff1f7000)
	libboost_regex.so.1.65.1 => /usr/lib/x86_64-linux-gnu/libboost_regex.so.1.65.1 (0x00007f6dfeeef000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f6dfeb66000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f6dfe94e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6dfe55d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6dff655000)
	libicui18n.so.60 => /usr/lib/x86_64-linux-gnu/libicui18n.so.60 (0x00007f6dfe0bc000)
	libicuuc.so.60 => /usr/lib/x86_64-linux-gnu/libicuuc.so.60 (0x00007f6dfdd05000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6dfd967000)
	libicudata.so.60 => /usr/lib/x86_64-linux-gnu/libicudata.so.60 (0x00007f6dfbdbe000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6dfbbba000)
`

**Comment by GerdHel** [comment]
The issue has been caused by a boost version mismatch on system. I had simultaneously installed the official boost package for bionic beaver (libboost-all-dev, boost version 1.65.1) and boost version 1.69.0 from source. Seems so that catkin has used boost version 1.65.1 to link the libsm_logging.so. After de-installation of libboost-all-dev, de-installation of ros-melodic, rebuilding boost 1.69.0 from source, reinstalling ros-melodic and rebuilding kalibr with catkin, `kalibr_calibrate_imu_camera` works as expected.
