### ISSUE TITLE
 bagcreater error. "ValueError: invalid literal for int() with base 10"

### ISSUE THREAD

**Issue by ihtishamaliktk** [ethz-asl/kalibr#286]
I am getting this error when I try to create a bag for using the Kalibr toolkit.  I can extract data from the bag file as well. However, when I try to write a bag file for new data I get the following error.  I am using the CDE package on virtualbox. 
> Original exception was:
> Traceback (most recent call last):
>   File "/var/kalibr-build/devel/bin/kalibr_bagcreater", line 5, in <module>
>     exec(fh.read())
>   File "<string>", line 121, in <module>
>   File "<string>", line 87, in createImuMessge
> ValueError: invalid literal for int() with base 10: ''

 The error arises from the imu file but I can't figure it out why. The imu data in csv file is arranged as instructed:

timestamp,omega_x,omega_y,omega_z,alpha_x,alpha_y,alpha_z
1000000,0.013680000,0.001240000,0.003730000,1.227720000,-0.334780000,9.734500000
5000000,0.007460000,0.001240000,0.001240000,1.213990000,-0.329900000,9.734190000
10000000,-0.004970000,0.001240000,0.003730000,1.218570000,-0.344240000,9.729610000
15000000,-0.011190000,0.000000000,0.003730000,1.216740000,-0.348510000,9.735720000
.
.

**Comment by ihtishamaliktk** [comment]
problem was that my timestamp was in microseconds. As soon as I converted it into nanoseconds, it worked fine.
