### ISSUE TITLE
kalibr_calibrate_cameras NameError: global name 'errList' is not defined

### ISSUE THREAD

**Issue by zsk194189650** [ethz-asl/kalibr#370]
Hello,when use kalibr_calibrate_cameras, there is an err like this: 

sycon@Sycon:~/kalibr_ws$ kalibr_calibrate_cameras --bag fisheye_calibra.bag --topics /left --models pinhole-radtan --target april_3x2_5cm_A1.yaml
importing libraries
Initializing cam0:
	Camera model:	  pinhole-radtan
	Dataset:          fisheye_calibra.bag
	Topic:            /left
	Number of images: 191
Traceback (most recent call last):
  File "/home/sycon/kalibr_ws/devel/bin/kalibr_calibrate_cameras", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/sycon/kalibr_ws/src/kalibr/aslam_offline_calibration/kalibr/python/kalibr_calibrate_cameras", line 447, in <module>
    main()
  File "/home/sycon/kalibr_ws/src/kalibr/aslam_offline_calibration/kalibr/python/kalibr_calibrate_cameras", line 172, in main
    cam = kcc.CameraGeometry(cameraModel, targetConfig, dataset, verbose=(parsed.verbose or parsed.showextraction))
  File "/home/sycon/kalibr_ws/src/kalibr/aslam_offline_calibration/kalibr/python/kalibr_camera_calibration/CameraCalibrator.py", line 47, in __init__
    self.ctarget = TargetDetector(targetConfig, self.geometry, showCorners=verbose, showReproj=verbose)
  File "/home/sycon/kalibr_ws/src/kalibr/aslam_offline_calibration/kalibr/python/kalibr_camera_calibration/CameraCalibrator.py", line 80, in __init__
    targetParams = targetConfig.getTargetParams()
  File "/home/sycon/kalibr_ws/src/kalibr/aslam_offline_calibration/kalibr/python/kalibr_common/ConfigReader.py", line 186, in func
    return f(*args, **kwargs)
  File "/home/sycon/kalibr_ws/src/kalibr/aslam_offline_calibration/kalibr/python/kalibr_common/ConfigReader.py", line 610, in getTargetParams
    errList.append("invalid tagRows (int>=3)")
NameError: global name 'errList' is not defined

Can anyone tell me why it happened and how to solve it.
Thanks!

**Comment by zsk194189650** [comment]
The size of roapriltag must be greater than 3*3.

**Comment by heisetiantang** [comment]
![微信图片_20221110220217](https://user-images.githubusercontent.com/92718554/201111878-e1602aab-2742-4df8-88c5-2bcd7cd10e23.jpg)
![微信图片_20221110220225](https://user-images.githubusercontent.com/92718554/201111892-7bb80d3d-fbad-4b46-b8dc-4b352a19de4d.jpg)
![微信图片_20221110220228](https://user-images.githubusercontent.com/92718554/201111899-12285c1f-d57f-45a0-b895-1f06d20e350c.jpg)
![微信图片_20221110220231](https://user-images.githubusercontent.com/92718554/201111902-1ad99e8d-7c7f-4513-ab57-7c1f5ac897c0.jpg)


我与作者出现了相同的问题，我的标定板是8×6的，是大于3×3的，为什么任然出现上述问题，是否可能因为april的命名方式，必须加上a*b和每一格的大小，


I have the same problem with the author. My calibration plate is 8×6, which is larger than 3×3. Why does the above problem still occur?

**Comment by wbl17792615320** [comment]
I am not very understand, but I am glad that I have solved the problem, my Ubuntu system is 18.04, should be related to the installation problems, must adapt to their own system, if you are 18.04 system, can follow this tutorial to do :https://blog.csdn.net/ndwonduosk_/article/details/124718186?spm=1001.2014.3001.5506
18.04Do not use the catkin _ make command
