### ISSUE TITLE
ImportError: No module named wxversion

### ISSUE THREAD

**Issue by sooroosh** [ethz-asl/kalibr#386]
Hi,
I would like to calibrate an omnidirectional camera with Kalibr. I am interested in the eucm model which is not included in the CDE-package. I installed Kalibr from the source with Ubuntu 16.04 and Ros kinetic. I have made a virtual envronment with a python 2.7 installation. I have successfully installed all the 37 packages. However, when I try to run the calibration tool I get the following error:

> Traceback (most recent call last):
  File "/home/soroush/kalibr_workspace/devel/bin/kalibr_calibrate_cameras", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/soroush/kalibr_workspace/src/Kalibr/aslam_offline_calibration/kalibr/python/kalibr_calibrate_cameras", line 7, in <module>
    from sm import PlotCollection
  File "/home/soroush/kalibr_workspace/src/Kalibr/Schweizer-Messer/sm_python/python/sm/PlotCollection.py", line 1, in <module>
    import wxversion
ImportError: No module named wxversion

I have tried to install wxpython package (which should contain wxversion) with conda and pip but it did not help. Is there anyone who knows a workaround for this ? I have been trying to solve this for a couple of days now without luck. Sorry if this issue is not directly related to the toolbox.

**Comment by sooroosh** [comment]
Just removed the first two lines in "kalibr_workspace/src/Kalibr/Schweizer-Messer/sm_python/python/sm/PlotCollection.py" and surpassed the error !
