### ISSUE TITLE
Crashing while calibrating

### ISSUE THREAD

**Issue by mehditlili** [ethz-asl/kalibr#403]
On Ubuntu 18.04
`kalibr_calibrate_cameras --bag 2020-12-14-11-14-16.bag --topic /camera/image_raw --model pinhole-radtan --target aprilgrid.yaml `

```
Traceback (most recent call last):
  File "/home/mehdi/Workspaces/wemo_ws/devel/bin/kalibr_calibrate_cameras", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/mehdi/Workspaces/wemo_ws/src/kalibr/aslam_offline_calibration/kalibr/python/kalibr_calibrate_cameras", line 447, in <module>
    main()
  File "/home/mehdi/Workspaces/wemo_ws/src/kalibr/aslam_offline_calibration/kalibr/python/kalibr_calibrate_cameras", line 204, in main
    graph.plotGraph()
  File "/home/mehdi/Workspaces/wemo_ws/src/kalibr/aslam_offline_calibration/kalibr/python/kalibr_camera_calibration/MulticamGraph.py", line 311, in plotGraph
    edge_label=self.G.es["weight"],
KeyError: 'Attribute does not exist'
```

**Comment by goldbattle** [comment]
Can you see if PR https://github.com/ethz-asl/kalibr/pull/515 fixes the issue for you?
What version of igraph do you have installed?
