### ISSUE TITLE
Separate accelerometer and gyroscope topics in D455

### ISSUE THREAD

**Issue by mateosss** [ethz-asl/kalibr#458]
Hello, I have a Realsense D455, I'm using the realsense-viewer to record a rosbag file. Unfortunately this camera provides separate accelerometer (at 63hz and 250hz) and gyroscope (at 200hz and 400hz) IMU ROS topics, each with zero values for the other sensor: 

<details><summary>Example of published data for the accelerometer</summary>

```
%time,field.header.seq,field.header.stamp,field.header.frame_id,field.orientation.x,field.orientation.y,field.orientation.z,field.orientation.w,field.orientation_covariance0,field.orientation_covariance1,field.orientation_covariance2,field.orientation_covariance3,field.orientation_covariance4,field.orientation_covariance5,field.orientation_covariance6,field.orientation_covariance7,field.orientation_covariance8,field.angular_velocity.x,field.angular_velocity.y,field.angular_velocity.z,field.angular_velocity_covariance0,field.angular_velocity_covariance1,field.angular_velocity_covariance2,field.angular_velocity_covariance3,field.angular_velocity_covariance4,field.angular_velocity_covariance5,field.angular_velocity_covariance6,field.angular_velocity_covariance7,field.angular_velocity_covariance8,field.linear_acceleration.x,field.linear_acceleration.y,field.linear_acceleration.z,field.linear_acceleration_covariance0,field.linear_acceleration_covariance1,field.linear_acceleration_covariance2,field.linear_acceleration_covariance3,field.linear_acceleration_covariance4,field.linear_acceleration_covariance5,field.linear_acceleration_covariance6,field.linear_acceleration_covariance7,field.linear_acceleration_covariance8
1241,111816,1628683551900585651,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2730751633644104,-9.641128540039062,0.9453434944152832,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3295001,111817,1628683551904450655,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2521442174911499,-9.70188045501709,1.0066514015197754,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7734312,111818,1628683551908315897,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2926884889602661,-9.721549034118652,0.9459573030471802,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10997794,111819,1628683551912180185,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2723960280418396,-9.762004852294922,0.9472370147705078,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15082945,111820,1628683551916045189,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3327181339263916,-9.801704406738281,0.9061142206192017,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18922011,111821,1628683551919909477,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.35290801525115967,-9.8417329788208,0.8662885427474976,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22982334,111822,1628683551923773527,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3533201813697815,-9.86172866821289,0.806891679763794,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26596627,111823,1628683551927638769,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3739115595817566,-9.861414909362793,0.7465305328369141,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30867243,111824,1628683551931503773,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3541700839996338,-9.881600379943848,0.6977343559265137,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...
```
</details>

Would it be correct to use these topics as two separate IMUs and put, for example for the accelerometer, 1.0 for the `gyroscope_noise_density` and `gyroscope_random_walk`, and vice-versa? Or that won't work and it is necessary to merge the two readings somehow. If so, how would you recommend doing that?

<details>
<summary>EDIT: I'm getting an optimization failure when using them as two separate IMUs:</summary>

```bash
root@150d4f412ccc:~/data/fifth-2min# kalibr_calibrate_imu_camera \
> --target april_6x6_80x80cm_A4.yaml \
> --bag 2min.bag \
> --cam results/camchain-2min.yaml \
> --imu BMI055-gyro.yaml BMI055-accel.yaml \
> --imu-models calibrated calibrated \
> 
importing libraries
Initializing IMUs:
  Update rate: 200.0
  Accelerometer:
    Noise density: 1.0 
    Noise density (discrete): 14.1421356237 
    Random walk: 1.0
  Gyroscope:
    Noise density: 0.0025
    Noise density (discrete): 0.0353553390593 
    Random walk: 4e-05
Initializing imu rosbag dataset reader:
	Dataset:          2min.bag
	Topic:            /device_0/sensor_2/Gyro_0/imu/data
	Number of messages: 28320
Reading IMU data (/device_0/sensor_2/Gyro_0/imu/data)
  Read 28320 imu readings over 141.4 seconds                         
  Update rate: 250.0
  Accelerometer:
    Noise density: 0.14 
    Noise density (discrete): 2.21359436212 
    Random walk: 0.002
  Gyroscope:
    Noise density: 1.0
    Noise density (discrete): 15.8113883008 
    Random walk: 1.0
Initializing imu rosbag dataset reader:
	Dataset:          2min.bag
	Topic:            /device_0/sensor_2/Accel_0/imu/data
	Number of messages: 36476
Reading IMU data (/device_0/sensor_2/Accel_0/imu/data)
  Read 36476 imu readings over 141.4 seconds                         
Initializing calibration target:
  Type: aprilgrid
  Tags: 
    Rows: 6
    Cols: 6
    Size: 0.022 [m]
    Spacing 0.0066 [m]
Initializing camera chain:
Camera chain - cam0:
  Camera model: pinhole
  Focal length: [323.9528165157555, 325.75589200305274]
  Principal point: [322.0501706006063, 179.84652110800093]
  Distortion model: radtan
  Distortion coefficients: [0.005404218584566168, -0.004629491468181238, -0.001511690906595974, 0.002526994630394859]
  baseline: no data available
Camera chain - cam1:
  Camera model: pinhole
  Focal length: [323.79814549684494, 325.29177455282655]
  Principal point: [321.00488853200835, 180.06231298411643]
  Distortion model: radtan
  Distortion coefficients: [0.006373903388221828, -0.00545103805293005, -0.0011927578473224345, 0.0015229284332734536]
  baseline: [[ 0.99999204  0.0005544   0.00395159 -0.09501444]
 [-0.00055305  0.99999979 -0.00034156 -0.00019336]
 [-0.00395178  0.00033937  0.99999213 -0.00056311]
 [ 0.          0.          0.          1.        ]]
Camera chain - cam2:
  Camera model: pinhole
  Focal length: [318.2455743333185, 319.1053651874527]
  Principal point: [321.03087032905177, 184.9507781157298]
  Distortion model: radtan
  Distortion coefficients: [-0.04849950281839186, 0.039198905850420185, -0.0014904021095707549, 0.0023338989156013053]
  baseline: [[ 0.99999996  0.00004541  0.00027911  0.03605163]
 [-0.00004559  0.99999981  0.00062207 -0.00011908]
 [-0.00027908 -0.00062208  0.99999977 -0.00109261]
 [ 0.          0.          0.          1.        ]]
Initializing camera rosbag dataset reader:
	Dataset:          2min.bag
	Topic:            /device_0/sensor_0/Infrared_1/image/data
	Number of images: 4241
Extracting calibration target corners
  Extracted corners for 3867 images (of 4241 images)                              
Initializing camera rosbag dataset reader:
	Dataset:          2min.bag
	Topic:            /device_0/sensor_0/Infrared_2/image/data
	Number of images: 4241
Extracting calibration target corners
  Extracted corners for 3942 images (of 4241 images)                              
Initializing camera rosbag dataset reader:
	Dataset:          2min.bag
	Topic:            /device_0/sensor_1/Color_0/image/data
	Number of images: 4241
Extracting calibration target corners
  Extracted corners for 3509 images (of 4241 images)                              
Baseline between cam0 and cam1 set to:
T=  [[ 0.99999204  0.0005544   0.00395159 -0.09501444]
 [-0.00055305  0.99999979 -0.00034156 -0.00019336]
 [-0.00395178  0.00033937  0.99999213 -0.00056311]
 [ 0.          0.          0.          1.        ]]
Baseline:  0.0950163015762  [m]
Baseline between cam1 and cam2 set to:
T=  [[ 0.99999996  0.00004541  0.00027911  0.03605163]
 [-0.00004559  0.99999981  0.00062207 -0.00011908]
 [-0.00027908 -0.00062208  0.99999977 -0.00109261]
 [ 0.          0.          0.          1.        ]]
Baseline:  0.0360683812362  [m]

Estimating imu-imu rotation initial guess.
Temporal correction with respect to reference IMU 
0.0 [s]  (this offset is not accounted for in the calibration)
Estimated imu to reference imu Rotation: 
[[ 1.  0. -0.]
 [-0.  1. -0.]
 [ 0.  0.  1.]]

Building the problem
	Spline order: 6
	Pose knots per second: 100
	Do pose motion regularization: False
		xddot translation variance: 1000000.000000
		xddot rotation variance: 100000.000000
	Bias knots per second: 50
	Do bias motion regularization: True
	Blake-Zisserman on reprojection errors -1
	Acceleration Huber width (sigma): -1.000000
	Gyroscope Huber width (sigma): -1.000000
	Do time calibration: True
	Max iterations: 30
	Time offset padding: 0.030000
Estimating time shift camera to imu:

Initializing a pose spline with 14140 knots (100.000000 knots per second over 141.399154 seconds)
  Time shift camera to imu (t_imu = t_cam + shift):
-0.00499394467929
Estimating time shift camera to imu:

Initializing a pose spline with 14140 knots (100.000000 knots per second over 141.399154 seconds)
  Time shift camera to imu (t_imu = t_cam + shift):
-0.00499394467929
Estimating time shift camera to imu:

Initializing a pose spline with 14139 knots (100.000000 knots per second over 141.393675 seconds)
  Time shift camera to imu (t_imu = t_cam + shift):
-0.00998788935859

Estimating imu-camera rotation prior

Initializing a pose spline with 14140 knots (100.000000 knots per second over 141.399154 seconds)
/kalibr_workspace/src/Kalibr/aslam_offline_calibration/kalibr/python/kalibr_imu_camera_calibration/IccSensors.py:188: RuntimeWarning: invalid value encountered in divide
  self.gravity_w = mean_a_w / np.linalg.norm(mean_a_w) * 9.80655
Gravity was intialized to [ nan  nan  nan] [m/s^2]
  Orientation prior camera-imu found as: (T_i_c)
[[ 0.99996396 -0.00141885 -0.00837092]
 [ 0.00141209  0.99999867 -0.00081379]
 [ 0.00837207  0.00080194  0.99996463]]
  Gyro bias prior found as: (b_gyro)
[-0.00233667  0.00259213  0.00177288]

Initializing a pose spline with 14152 knots (100.000000 knots per second over 141.519154 seconds)

Initializing the bias splines with 7076 knots

Initializing the bias splines with 7076 knots

Adding camera error terms (/device_0/sensor_0/Infrared_1/image/data)
  Added 3867 camera error terms                               

Adding camera error terms (/device_0/sensor_0/Infrared_2/image/data)
  Added 3942 camera error terms                               

Adding camera error terms (/device_0/sensor_1/Color_0/image/data)
  Added 3509 camera error terms                               

Adding accelerometer error terms (/device_0/sensor_2/Gyro_0/imu/data)
  Added 28320 of 28320 accelerometer error terms (skipped 0 out-of-bounds measurements)

Adding gyroscope error terms (/device_0/sensor_2/Gyro_0/imu/data)
  Added 28320 of 28320 gyroscope error terms (skipped 0 out-of-bounds measurements)

Adding accelerometer error terms (/device_0/sensor_2/Accel_0/imu/data)
  Added 36476 of 36476 accelerometer error terms (skipped 0 out-of-bounds measurements)

Adding gyroscope error terms (/device_0/sensor_2/Accel_0/imu/data)
  Added 36476 of 36476 gyroscope error terms (skipped 0 out-of-bounds measurements)

Before Optimization
===================
Normalized Residuals
----------------------------
Reprojection error (cam0):     mean 0.363509076058, median 0.296452399763, std: 0.267786185679
Reprojection error (cam1):     mean 0.387028345911, median 0.319259038063, std: 0.289233193312
Reprojection error (cam2):     mean 0.38736705883, median 0.3199371175, std: 0.282904895863
Gyroscope error (imu0):        mean 1.4082525802, median 1.15725237714, std: 1.0242169168
/usr/lib/python2.7/dist-packages/numpy/lib/function_base.py:3558: RuntimeWarning: Invalid value encountered in median
  RuntimeWarning)
Accelerometer error (imu0):    mean nan, median nan, std: nan
Gyroscope error (imu1):        mean 0.019222412946, median 0.01829544262, std: 0.0159150680186
Accelerometer error (imu1):    mean nan, median nan, std: nan

Residuals
----------------------------
Reprojection error (cam0) [px]:     mean 0.363509076058, median 0.296452399763, std: 0.267786185679
Reprojection error (cam1) [px]:     mean 0.387028345911, median 0.319259038063, std: 0.289233193312
Reprojection error (cam2) [px]:     mean 0.38736705883, median 0.3199371175, std: 0.282904895863
Gyroscope error (imu0) [rad/s]:     mean 0.0497892474542, median 0.0409150501709, std: 0.0362115363637
Accelerometer error (imu0) [m/s^2]: mean nan, median nan, std: nan
Gyroscope error (imu1) [rad/s]:     mean 0.303933035169, median 0.2892763474, std: 0.251639320276
Accelerometer error (imu1) [m/s^2]: mean nan, median nan, std: nan

Optimizing...
Using the block_cholesky linear system solver
Using the levenberg_marquardt trust region policy
Using the block_cholesky linear system solver
Using the levenberg_marquardt trust region policy
Initializing
Optimization problem initialized with 42489 design variables and 1446051 error terms
The Jacobian matrix is 3021690 x 169931
[0.0]: J: -nan
CHOLMOD warning: matrix not positive definite
[WARNING] System solution failed
CHOLMOD warning: matrix not positive definite
[WARNING] System solution failed
CHOLMOD warning: matrix not positive definite
[WARNING] System solution failed
CHOLMOD warning: matrix not positive definite
[WARNING] System solution failed
CHOLMOD warning: matrix not positive definite
[WARNING] System solution failed
CHOLMOD warning: matrix not positive definite
[WARNING] System solution failed
CHOLMOD warning: matrix not positive definite
[WARNING] System solution failed
CHOLMOD warning: matrix not positive definite
[WARNING] System solution failed
CHOLMOD warning: matrix not positive definite
[WARNING] System solution failed
CHOLMOD warning: matrix not positive definite
[WARNING] System solution failed
CHOLMOD warning: matrix not positive definite
[WARNING] System solution failed
CHOLMOD warning: matrix not positive definite
[WARNING] System solution failed
CHOLMOD warning: matrix not positive definite
[WARNING] System solution failed
CHOLMOD warning: matrix not positive definite
[WARNING] System solution failed
CHOLMOD warning: matrix not positive definite
[WARNING] System solution failed
CHOLMOD warning: matrix not positive definite
[WARNING] System solution failed
CHOLMOD warning: matrix not positive definite
[WARNING] System solution failed
CHOLMOD warning: matrix not positive definite
[WARNING] System solution failed
CHOLMOD warning: matrix not positive definite
[WARNING] System solution failed
CHOLMOD warning: matrix not positive definite
[WARNING] System solution failed
CHOLMOD warning: matrix not positive definite
[WARNING] System solution failed
CHOLMOD warning: matrix not positive definite
[WARNING] System solution failed
CHOLMOD warning: matrix not positive definite
[WARNING] System solution failed
CHOLMOD warning: matrix not positive definite
[WARNING] System solution failed
CHOLMOD warning: matrix not positive definite
[WARNING] System solution failed
CHOLMOD warning: matrix not positive definite
[WARNING] System solution failed
CHOLMOD warning: matrix not positive definite
[WARNING] System solution failed
CHOLMOD warning: matrix not positive definite
[WARNING] System solution failed
CHOLMOD warning: matrix not positive definite
[WARNING] System solution failed
CHOLMOD warning: matrix not positive definite
[WARNING] System solution failed
[ERROR] [1628696111.973950]: Optimization failed!
Traceback (most recent call last):
  File "/kalibr_workspace/devel/bin/kalibr_calibrate_imu_camera", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/kalibr_workspace/src/Kalibr/aslam_offline_calibration/kalibr/python/kalibr_calibrate_imu_camera", line 236, in <module>
    main()
  File "/kalibr_workspace/src/Kalibr/aslam_offline_calibration/kalibr/python/kalibr_calibrate_imu_camera", line 206, in main
    iCal.optimize(maxIterations=parsed.max_iter, recoverCov=parsed.recover_cov)
  File "/kalibr_workspace/src/Kalibr/aslam_offline_calibration/kalibr/python/kalibr_imu_camera_calibration/IccCalibrator.py", line 179, in optimize
    raise RuntimeError("Optimization failed!")
RuntimeError: Optimization failed!
root@150d4f412ccc:~/data/fifth-2min# 
```
</details>

**Comment by goldbattle** [comment]
You need to specify the following in your realsense launch to combine the two topics:
```
<arg name="unite_imu_method" default="linear_interpolation"/>
```

The two original topics publish only have the gyroscope or accelerometer portion in each topics, thus are not valid IMUs that can be calibrated through kalibr.
