### ISSUE TITLE
package 'igraph' is deprecated

### ISSUE THREAD

**Issue by CogmanCVN** [ethz-asl/kalibr#466]
Hello, I encountered the following problems when using the **kalibr_calibrate_cameras** tool:
kalibr_calibrate_cameras --target april_6x6.yaml --bag static.bag --models pinhole-equi pinhole-equi omni-radtan omni-radtan --topics /cam0/image_raw /cam1/image_raw /cam2/image_raw /cam3/image_raw

Traceback (most recent call last):
  File "/home/zqy/kalibr_workspace/devel/bin/kalibr_calibrate_cameras", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/zqy/kalibr_workspace/src/Kalibr/aslam_offline_calibration/kalibr/python/kalibr_calibrate_cameras", line 12, in <module>
    import kalibr_camera_calibration as kcc
  File "/home/zqy/kalibr_workspace/src/Kalibr/aslam_offline_calibration/kalibr/python/kalibr_camera_calibration/__init__.py", line 4, in <module>
    from ObsDb import *
  File "/home/zqy/kalibr_workspace/src/Kalibr/aslam_offline_calibration/kalibr/python/kalibr_camera_calibration/ObsDb.py", line 6, in <module>
    import igraph
  File "/home/zqy/.local/lib/python2.7/site-packages/igraph/__init__.py", line 8, in <module>
    warn_deprecation()
  File "/home/zqy/.local/lib/python2.7/site-packages/igraph/_utils.py", line 36, in warn_deprecation
    raise RuntimeError("This package is deprecated. See the deprecation notice above.")
RuntimeError: This package is deprecated. See the deprecation notice above.

My environment is Ubuntu 8.04 and python 3.7. I need help, thanks.

**Comment by mhyoosefian** [comment]
Hi.
Have you tried 
`sudo apt-get upgrade pytohn-igraph`
?

**Comment by CogmanCVN** [comment]
Can't solve...

**Comment by CrisXin000** [comment]
Maybe you can try 
`sudo pip uninstall igraph`
`sudo apt install python-igraph`
it is work for me.

**Comment by Tsingkai** [comment]
The same exception……QAQ
Everything isn't  work for me!
Please the world Die!

**Comment by JazzyFeng** [comment]
> Maybe you can try `sudo pip uninstall igraph` `sudo apt install python-igraph` it is work for me.

You saved my life!

**Comment by lemoncoffe** [comment]
> 

It is great ！Thanks！

**Comment by goldbattle** [comment]
Hi please try PR https://github.com/ethz-asl/kalibr/pull/515 to see if that solves your issue.

**Comment by kanhao100** [comment]
> Maybe you can try `sudo pip uninstall igraph` `sudo apt install python-igraph` it is work for me.

Thank you very much!
