### ISSUE TITLE
Kalibr in RPi

### ISSUE THREAD

**Issue by andriilitvynchuk** [ethz-asl/kalibr#720]
I build the docker for RPi with this Dockerfile: https://github.com/droneoperations/kalibr/blob/master/Dockerfile_ros1_20_04

Then I run it like this:

```
docker run -v "$PWD:/catkin_ws/vnd" -v "$PWD/sources/calibration:/catkin_ws/files" -it andriilitvynchuk8/kalibr:arm64-latest
```
Inside, running this:
```
rosrun kalibr kalibr_calibrate_cameras --models pinhole-equi --topics /cam0/image_raw \
>   --bag vnd/calibration/calibration.bag --target files/april_6x6.yaml --no-outliers-removal --dont-show-report
```

leads to multiprocessing error:
```
importing libraries
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(kalibr_calibrate_cameras:355): Gdk-CRITICAL **: 09:16:39.164: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Initializing cam0:
	Camera model:	  pinhole-equi
	Dataset:          vnd/calibration/calibration.bag
	Topic:            /cam0/image_raw
	Number of images: 753
Extracting calibration target corners
  Progress 3 / 753 	 Time remaining: 1 h 58m 53s                  Process Process-3:
Process Process-5:
Process Process-4:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/catkin_ws/src/kalibr/aslam_offline_calibration/kalibr/python/kalibr_common/TargetExtractor.py", line 17, in multicoreExtractionWrapper
    task = taskq.get_nowait()
  File "<string>", line 2, in get_nowait
  File "/usr/lib/python3.8/multiprocessing/managers.py", line 834, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/catkin_ws/src/kalibr/aslam_offline_calibration/kalibr/python/kalibr_common/TargetExtractor.py", line 17, in multicoreExtractionWrapper
    task = taskq.get_nowait()
  File "/catkin_ws/src/kalibr/aslam_offline_calibration/kalibr/python/kalibr_common/TargetExtractor.py", line 17, in multicoreExtractionWrapper
    task = taskq.get_nowait()
  File "<string>", line 2, in get_nowait
  File "<string>", line 2, in get_nowait
  File "/usr/lib/python3.8/multiprocessing/managers.py", line 834, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/usr/lib/python3.8/multiprocessing/managers.py", line 834, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/catkin_ws/src/kalibr/aslam_offline_calibration/kalibr/python/kalibr_common/TargetExtractor.py", line 68, in extractCornersFromDataset
    done = numImages-taskq.qsize()
  File "<string>", line 2, in qsize
  File "/usr/lib/python3.8/multiprocessing/managers.py", line 835, in _callmethod
    kind, result = conn.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/catkin_ws/devel/lib/kalibr/kalibr_calibrate_cameras", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/catkin_ws/src/kalibr/aslam_offline_calibration/kalibr/python/kalibr_calibrate_cameras", line 465, in <module>
    main()
  File "/catkin_ws/src/kalibr/aslam_offline_calibration/kalibr/python/kalibr_calibrate_cameras", line 179, in main
    observations = kc.extractCornersFromDataset(cam.dataset, cam.ctarget.detector, 
  File "/catkin_ws/src/kalibr/aslam_offline_calibration/kalibr/python/kalibr_common/TargetExtractor.py", line 76, in extractCornersFromDataset
    raise RuntimeError("Exception during multithreaded extraction: {0}".format(e))
RuntimeError: Exception during multithreaded extraction: [Errno 104] Connection reset by peer
```
What am I doing wrong?

**Comment by andriilitvynchuk** [comment]
It looks like 3 processes is too much for RAM of RPi
