### ISSUE TITLE
ImportError: No module named apport.fileutils

### ISSUE THREAD

**Issue by kilmarnock** [ethz-asl/kalibr#77]
Hi!
When I try to run `kalibr_calibrate_cameras ...`
I get the error 
`ImportError: No module named apport.fileutils`
I use the cde binary on ubuntu 14.04. 
Unfortunatelly I do not know anything about cde. What can I do? Ubuntu has apport installed. 

The Stacktrace is
`importing libraries
Traceback (most recent call last):
  File "/var/kalibr-build/devel/bin/kalibr_calibrate_cameras", line 5, in <module>
    exec(fh.read())
  File "<string>", line 444, in <module>
  File "<string>", line 149, in main
  File "/var/kalibr-build/src/kalibr/aslam_offline_calibration/kalibr/python/kalibr_common/ConfigReader.py", line 397, in __init__
    ParametersBase.__init__(self, yamlFile, "CalibrationTargetConfig", createYaml)
  File "/var/kalibr-build/src/kalibr/aslam_offline_calibration/kalibr/python/kalibr_common/ConfigReader.py", line 135, in __init__
    self.data = self.readYaml()
  File "/var/kalibr-build/src/kalibr/aslam_offline_calibration/kalibr/python/kalibr_common/ConfigReader.py", line 146, in readYaml
    self.raiseError( "Could not read configuration from {0}".format(self.yamlFile) )
  File "/var/kalibr-build/src/kalibr/aslam_offline_calibration/kalibr/python/kalibr_common/ConfigReader.py", line 169, in raiseError
    raise RuntimeError( "{0}{1}".format(header, message) )
RuntimeError: [CalibrationTargetConfig Reader]: Could not read configuration from /mnt/256GBSDCard/schachbrett_kalibr.yamls
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/apport_python_hook.py", line 64, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
ImportError: No module named apport.fileutils
`

**Comment by kilmarnock** [comment]
Never mind. It happens if you messs the arguments. Sorry.

**Comment by MF1523017** [comment]
how do you solve the problem?

**Comment by JHartzer** [comment]
The error is likely caused by an incorrect parameter in the yaml files such as setting the target_type parameter to aprilgrid instead of checkerboard. Ensure that you have the correct target type and size.
