### ISSUE TITLE
Running with ROS Indigo

### ISSUE THREAD

**Issue by stefangachter** [ethz-asl/kalibr#9]
Running the calibration with the provided data fails with the following error:

    user@psc:$ kalibr_calibrate_imu_camera --bag dynamic.bag --cam camchain.yaml --imu imu_adis16448.yaml --target april_6x6.yaml 
    ...
    Extracting calibration target corners
    Traceback (most recent call last):
    File "/Workspace/Catkin/devel/bin/kalibr_calibrate_imu_camera", line 5, in <module>
    exec(fh.read())
    File "<string>", line 206, in <module>
    File "<string>", line 149, in main
    File "/Workspace/Catkin/src/Kalibr/aslam_offline_calibration/kalibr/python/kalibr_imu_camera_calibration/IccSensors.py", line 391, in __init__
    showOneStep=parsed.extractionstepping) )  
    File "/Workspace/Catkin/src/Kalibr/aslam_offline_calibration/kalibr/python/kalibr_imu_camera_calibration/IccSensors.py", line 59, in __init__
    self.targetObservations = kc.extractCornersFromDataset(self.dataset, self.detector, multithreading=multithreading)
    File "/Workspace/Catkin/src/Kalibr/aslam_offline_calibration/kalibr/python
    /kalibr_common/TargetExtractor.py", line 73, in extractCornersFromDataset
    raise RuntimeError("Exception during multithreaded extraction: {0}".format(e))
    RuntimeError: Exception during multithreaded extraction: CvBridge instance has no attribute 'imgmsg_to_cv'

This error seems to be similar to
http://answers.ros.org/question/170971/issues-with-cv_bridge-when-using-cameracalibratorpy-in-indigo/

**Comment by jbohren** [comment]
+1 this fixes this bug for me too.

Thanks @stefangachter

**Comment by v0n0** [comment]
I am running `master` on Indigo with no problem, I think this can be closed.

**Comment by schneith** [comment]
Same here, running on Indigo without any issues. 

Thanks for the note, i'll close it.
